### ISSUE TITLE
Error ES6

### ISSUE THREAD

**Issue by candidoalbertosilva** [kisstar/electron-events#5]
I implemented it in an Electron project and it's returning this error.:

```
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/candidoalberto/Documents/aplicativos/menuvem/node_modules/lodash-es/lodash.js from /Users/candidoalberto/Documents/aplicativos/menuvem/node_modules/electron-events/dist-electron/index.js not supported.
Instead change the require of lodash.js in /Users/candidoalberto/Documents/aplicativos/menuvem/node_modules/electron-events/dist-electron/index.js to a dynamic import() which is available in all CommonJS modules.
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.<anonymous> (/Users/candidoalberto/Documents/aplicativos/menuvem/node_modules/electron-events/dist-electron/index.js:9:18)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Object.<anonymous> (/Users/candidoalberto/Documents/aplicativos/menuvem/.quasar/electron/electron-main.js:24:30)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
```

**Comment by kisstar** [comment]
It seems that you are using this package in CJS mode. There are indeed issues with this package in CJS mode. I will update a fixed version later. Please continue to try and provide feedback.
